2:2.c
	gcc 2.c -o 2.o
	./2.o > 2.txt

22:22.c
	gcc 22.c -o 22.o
	./22.o > 22.txt

3:3.c
	gcc 3.c -o 3.o

32:32.c
	gcc 32.c -o 32.o

4:4.c
	gcc 4.c -o 4.o

5:5.c
	gcc 5.c -o 5.o
	sudo chown root 5.o
	sudo chmod 4755 5.o

6:6.c
	gcc 6.c -o 6.o
	sudo chown root 6.o
	sudo chmod 4755 6.o

7:mylib.c
	gcc -fPIC -g -c mylib.c
	gcc -shared -o libmylib.so.1.0.1 mylib.o -lc

72:myprog.c
	gcc myprog.c -o myprog.o

8:8.c
	gcc 8.c -o 8.o
	sudo chown root 8.o
	sudo chmod 4755 8.o

82:82.c
	gcc 82.c -o 82.o
	sudo chown root 82.o
	sudo chmod 4755 82.o

9:9.c
	gcc 9.c -o 9.o
	sudo chown root 9.o
	sudo chmod 4755 9.o

92:92.c
	gcc 92.c -o 92.o
